version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: root2
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_DATABASE: FunToDraw_db
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/FunToDraw
      - public-data:/FunToDraw/public
      - tmp-data:/FunToDraw/tmp
      - log-data:/FunToDraw/log

    web:
      build:
        context: containers/nginx
      volumes:
        - public-data:/FunToDraw/public
        - tmp-data:/FunToDraw/tmp
      ports:
        - 80:80

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data:
